### ISSUE TITLE
Совместное редактирование проектов (project collaborators)

### ISSUE THREAD

**Issue by installero** [installero/qkspace#10]
Пользователь может добавить к своему проекту другого пользователя по email
Если такого email в базе нет, туда шлется письмо с предложением зарегистрироваться

**Comment by prisioner** [comment]
Предлагаю уточнить конкретную реализацию.

Какими правами должен обладать приглашенный пользователь?

1. Создание новых страниц
2. Редактирование существующих страниц
3. Удаление существующих страниц
4. Редактирование самого проекта (название, поддомен, домен (в будущем), google-аналитика)
5. Приглашение других коллабораторов
6. Удаление других коллабораторов
7. Удаление проекта

Если человек уже зарегистрирован должен ли он подтвердить приглашение или его сразу присоединяют к проекту?

Остаётся ли понятие владельца проекта ("projects"."user_id") или только список коллабораторов?
Обладает ли коллаборатор теми же правами, что и владелец или нет?
Если владелец проекта остаётся - должна ли быть функция передачи проекта другому владельцу (в рамках этой задачи)?
В рамках данной фичи уместным кажется введение soft delete или paper trail - нужно ли?

**Comment by installero** [comment]
Предлагаю так:

1. Да
2. Да
3. Да
4. Нет (чтобы не заморачиваться)
5. Нет
6. Нет (только сам может выпилиться)
7. Нет

Если зареган — добавляет сразу (см. пункт 6).

Понятие владельца — остается.

Колаборатор обладает другими правами (см. выше).

Функции передачи проекта нет.

Soft delete и paper trail пока не надо.

**Comment by EugZol** [comment]
#73
