### ISSUE TITLE
Общие куки для всех поддоменов (и основной зоны)

### ISSUE THREAD

**Issue by installero** [installero/qkspace#14]
Сейчас, если пользователь залогинен на [главной странице](qkspace.com), то на странице [проекта](http://ruby.qkspace.com/) он будет не авторизован и снова нужно будет логиниться.

Сделать так, чтобы куки были общие для всех поддоменов и не надо было логиниться в каждый проект отдельно.

**Comment by prisioner** [comment]
https://github.com/installero/qkspace/pull/28
