### ISSUE TITLE
Сделать возможность управления сайтом по хоткеям

### ISSUE THREAD

**Issue by EugZol** [installero/qkspace#39]

**Comment by prisioner** [comment]
Использовать управление хоткеями только в private или в public тоже? (понятно, что набор хоткеев отличается)

Какие хоткеи будем выделять? То, что приходит в голову:
P/N - Предыдущая/Следующая страница
E - Переход в режим редактирования

что ещё?)

**Comment by vergilsm** [comment]
Как показывать пользователю?

**Comment by prisioner** [comment]
#65
