### ISSUE TITLE
Ограничить названия поддоменов

### ISSUE THREAD

**Issue by EugZol** [installero/qkspace#44]
Запретить `www`, `blog`, `admin` (и подумать какие ещё), ограничить длинной от 5 символов.

**Comment by installero** [comment]
Мне кажется, одно другое исключает, т.к. все приведенные слаги 5 или короче :)

**Comment by prisioner** [comment]
https://github.com/michaldudek/subdomain-blacklist/blob/master/blacklist.txt

нашел список, от которого можно отталкиваться, и не все они короче 5 символов

**Comment by prisioner** [comment]
https://github.com/deanpcmad/saas_deny_subdomains/blob/master/lib/saas_deny_subdomains/subdomains.rb#L6

ещё список, частично повторяются с первым

**Comment by EugZol** [comment]
Мне кажется слишком сурово. Ну типа если кто-то зарегистрирует `about` или `beginner`, то и хорошо. Пунктов на 10, может на 20, список был бы хорош.

**Comment by prisioner** [comment]
Ну about стал бы хорошим доменом для страничке о самом qkspace :) 

В любом раскладе сократить готовый список проще чем с нуля придумать новый :)

**Comment by installero** [comment]
Предлагаю такой список:

```
about
admin
blog
demo
email
faq
support
www
```

Минимальную длину сделать 5

**Comment by prisioner** [comment]
я бы ещё дополнил типичными опечатками, а так же служебными словами типа

```
api
billing
buy
dev
download
ftp
help
mail
me
my
sftp
shop
smtp
ww
wwww
```

my/me когда-нибудь вполне могут стать личным кабинетом пользователя
help - по аналогии с support/faq
dev - если вдруг заведём стэйдж, то будет неплохим для него адресом вкупе с доп. авторизацией (basic_auth на уровне nginx или вроде того)
остальное может либо самим пригодиться либо быть использовано для введения в заблуждение)

**Comment by installero** [comment]
> я бы ещё дополнил типичными опечатками, а так же служебными словами типа

Не возражаю
