### ISSUE TITLE
Devise recoverable & confirmable

### ISSUE THREAD

**Issue by prisioner** [installero/qkspace#54]
### Связанная задача
Приглашение коллабораторов по email #10

### Проблема
Возможность несанкционированного доступа к редактированию чужих проектов путем регистрации на чужой email

### Задача
необходимо активировать функции из гема Devise для восстановления пароля и подтверждения почты при регистрации

### Implementation plan
1. Добавить в БД поля и индекс для модуля confirmable

```ruby
    ## Confirmable
    # t.string   :confirmation_token
    # t.datetime :confirmed_at
    # t.datetime :confirmation_sent_at
    # t.string   :unconfirmed_email # Only if using reconfirmable
    add_index :users, :confirmation_token,   unique: true
```
2. Активировать модули девайса recoverable & confirmable
3. Настроить отправку почты в инишалайзе Devise
4. Кастомизировать соответствующие вьюхи (включая partial shared/links)
5. *(опционально)* Кастомизировать шаблоны писем

**Comment by EugZol** [comment]
И настроить postfix. И к нему все нужные DNS, чтобы он проходил анти-спам проверки.
