### ISSUE TITLE
Скукожилась кнопка на форме регистрации

### ISSUE THREAD

**Issue by prisioner** [installero/qkspace#62]
![image](https://user-images.githubusercontent.com/28460079/47391281-10789d00-d722-11e8-8109-f9ef48acfac1.png)

Суть проблемы - кнопку рисует invisible_recaptcha_tag который ставить тэг button, для которого не определены нужные стили. Стили определены для input.

**Comment by installero** [comment]
![screenshot from 2018-10-24 11-04-25](https://user-images.githubusercontent.com/42387/47415654-a04b3500-d77c-11e8-846a-26cb839f3369.png)

Не понял. Это локально у тебя похоже.

http://qkspace.com/users/sign_up

**Comment by prisioner** [comment]
Нет, это рекапча ещё не задеплоена на прод :)
